export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL";
export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL";
export const SET_LOADING = "SET_LOADING";
export const LOGOUT = "LOGOUT";
export const GET_AUTH_USER = "GET_AUTH_USER";
export const AUTH_FAIL = "AUTH_FAIL";
export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const UPDATE_PROFILE_SUCCES = "UPDATE_PROFILE_SUCCES";
export const UPDATE_PROFILE_FAIL = "UPDATE_PROFILE_FAIL";
export const DELETE_COMMENT = "DELETE_COMMENT";
export const DELETE_COMMENT_SUCCES = "DELETE_COMMENT_SUCCES";
export const DELETE_COMMENT_FAIL = "DELETE_COMMENT_FAIL";

//action conducteur
export const GET_CONDUCTEUR_CARS_SUCCES = "GET_CONDUCTEUR_CAR_SUCCES";
export const GET_CONDUCTEUR_CARS_FAIL = "GET_CONDUCTEUR_CARS_FAIL";
export const SET_LOADING_CARS = "SET_LOADING_CARS";
export const ADD_CAR_SUCCES = "ADD_CAR_SUCCES";
export const ADD_CAR_FAIL = "ADD_CAR_FAIL";
export const DELETE_CAR_SUCCES = "DELETE_CAR_SUCCES";
export const DELETE_CAR_FAIL = "DELETE_CAR_FAIL";
export const GET_CONDUCTEUR_TRAJETS = "GET_CONDUCTEUR_TRAJETS";
export const GET_CONDUCTEUR_TRAJET_SUCCES = "GET_CONDUCTEUR_TRAJET_SUCCES";
export const GET_CONDUCTEUR_TRAJET_FAIL = "GET_CONDUCTEUR_TRAJET_FAIL";
export const ADD_CONDUCTEUR_TRAJET = "ADD_CONDUCTEUR_TRAJET";
export const ADD_CONDUCTEUR_TRAJET_SUCCES = "ADD_CONDUCTEUR_TRAJET_SUCCES";
export const ADD_CONDUCTEUR_TRAJET_FAIL = "ADD_CONDUCTEUR_TRAJET_FAIL";
export const DELETE_TRAJET_CONDUCTEUR = "DELETE_TRAJET_CONDUCTEUR";
export const DELETE_TRAJET_CONDUCTEUR_SUCCES =
  "DELETE_TRAJET_CONDUCTEUR_SUCCES";
export const DELETE_TRAJET_CONDUCTEUR_FAIL = "DELETE_TRAJET_CONDUCTEUR_FAIL";

//Passager action
export const GET_ALL_TRAJETS = "GET_ALL_TRAJETS";
export const GET_ALL_TRAJETS_SUCCES = "GET_ALL_TRAJETS_SUCCES";
export const GET_ALL_TRAJETS_FAIL = "GET_ALL_TRAJETS_FAIL";
export const RESERVE_TRAJET = "RESERVE_TRAJET";
export const RESERVE_TRAJET_SUCCES = "RESERVE_TRAJET_SUCCES";
export const RESERVE_TRAJET_FAIL = "RESERVE_TRAJET_FAIL";
export const GET_TRAJETS_RESERVER = "GET_TRAJETS_RESERVER";
export const GET_TRAJETS_RESERVER_SUCCES = "GET_TRAJETS_RESERVER_SUCCES";
export const GET_TRAJETS_RESERVER_FAIL = "GET_TRAJETS_RESERVER_FAIL";
export const ANNULER_TRAJET = "ANNULER_TRAJET";
export const ANNULER_TRAJET_SUCCES = "ANNULER_TRAJET_SUCCES";
export const ANNULER_TRAJET_FAIL = "ANNULER_TRAJET_FAIL";
export const GET_PROFILE = "GET_PROFILE";
export const GET_PROFILE_SUCCES = "GET_PROFILE_SUCCES";
export const GET_PROFILE_FAIL = "GET_PROFILE_FAIL";
export const ADD_COMMENT = "ADD_COMMENT";
export const ADD_COMMENT_SUCCES = "ADD_COMMENT_SUCCES";
export const ADD_COMMENT_FAIL = "ADD_COMMENT_FAIL";

//admin action
export const GET_ALL_CONDUCTEURS = "GET_ALL_CONDUCTEURS";
export const GET_ALL_CONDUCTEURS_SUCCES = "GET_ALL_CONDUCTEURS_SUCCES";
export const GET_ALL_CONDUCTEUR_FAIL = "GET_ALL_CONDUCTEUR_FAIL";
export const GET_ALL_PASSAGERS = "GET_ALL_PASSAGERS";
export const GET_ALL_PASSAGERS_SUCCES = "GET_ALL_PASSAGERS_SUCCES";
export const GET_ALL_PASSAGERS_FAIL = "GET_ALL_PASSAGERS_FAIL";
export const GET_ALL_TRAJET_ADMIN = "GET_ALL_TRAJET_ADMIN";
export const GET_ALL_TRAJET_ADMIN_SUCCES = "GET_ALL_TRAJET_ADMIN_SUCCES";
export const GET_ALL_TRAJET_ADMIN_FAIL = "GET_ALL_TRAJET_ADMIN_FAIL";
export const GET_TRAJET_BYID = "GET_TRAJET_BYID";
export const GET_TRAJET_BYID_SUCCES = "GET_TRAJET_BYID_SUCCES";
export const GET_TRAJET_BYID_FAIL = "GET_TRAJET_BYID_FAIL";
export const DELETE_USER = "DELETE_USER";
export const DELETE_USER_SUCCES = "DELETE_USER_SUCCES";
export const DELETE_USER_FAIL = "DELETE_USER_FAIL";
export const DELETE_TRAJET = "DELETE_TRAJET";
export const DELETE_TRAJET_SUCCES = "DELETE_TRAJET_SUCCES";
export const DELETE_TRAJET_FAIL = "DELETE_TRAJET_FAIL";
